dist: trusty
language: python
python:
  - "3.6"

install:
  - pip3 install PyQt5 pytest-xvfb

script:
  - pytest

after_success:
  - sudo apt-get update
  - sudo apt-get install doxygen
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $DOC_PAGES_TOKEN
  local_dir: docs/html/
  repo: Janonard/EngineL-docs
  target_branch: master